micronaut:
  application:
    name: advertisingData
  
  server:
    port: 8085
    max-request-size: 104857600 

datasources:
  default:
    url: jdbc:h2:mem:advertising;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''

flyway:
  datasources:
    default:
      enabled: true
      location: classpath:db/migration
      
advertising-data-source:
  uri: http://adverity-challenge.s3-website-eu-west-1.amazonaws.com/DAMKBAoDBwoDBAkOBAYFCw.csv
